import type { Metadata } from 'next';
import { Lato, Inter } from 'next/font/google';
import Navbar from '@/components/layout/Navbar';
import './globals.css';
import Footer from '@/components/layout/Footer';

const lato = Lato({
  variable: '--font-lato',
  subsets: ['latin'],
  weight: ['300', '400', '700', '900'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Fit & Wet',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${lato.variable} ${inter.variable} antialiased`}>
        <Navbar />
        <main className='min-h-[calc(100dvh-77px)]'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
