import type { Metadata } from 'next';
import { Teko } from 'next/font/google';
import Navbar from '@/components/layout/Navbar';
import './globals.css';

const teko = Teko({
  variable: '--font-teko',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Fit & Wet',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${teko.variable} antialiased`}>
        <Navbar />
        <main className='min-h-[calc(100dvh-77px)]'>{children}</main>
      </body>
    </html>
  );
}
